package com.example.ui

import android.app.Application
import android.content.Context
import android.print.PrintAttributes
import android.print.PrintManager
import android.webkit.WebView
import android.webkit.WebViewClient
import android.widget.Toast
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.example.data.*
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch
import java.io.File
import java.io.FileOutputStream
import java.util.Locale

class BudgetViewModel(application: Application) : AndroidViewModel(application) {

    private val repository: ProjectRepository
    val allProjects: StateFlow<List<Project>>

    // The currently active project
    val currentProject = MutableStateFlow<Project?>(null)

    // The working project data (being modified in the UI)
    val currentData = MutableStateFlow(ProjectData.createDefault())

    init {
        val database = AppDatabase.getDatabase(application)
        repository = ProjectRepository(database.projectDao())
        allProjects = repository.allProjects.stateIn(
            scope = viewModelScope,
            started = SharingStarted.WhileSubscribed(5000),
            initialValue = emptyList()
        )
    }

    // Set the current working project
    fun selectProject(project: Project) {
        currentProject.value = project
        currentData.value = project.data
    }

    // Unselect project and load default working data
    fun createNewProjectSession() {
        currentProject.value = null
        currentData.value = ProjectData.createDefault()
    }

    // Auto-generate 12 months based on custom parameters
    fun autoGenerateData(
        baseSalesQty: Double,
        growthPercent: Double,
        price: Double,
        rmCost: Double,
        laborRateVal: Double,
        varOverhead: Double,
        fixedOH: Double,
        fixedSA: Double,
        depr: Double,
        initCashVal: Double
    ) {
        currentData.value = ProjectData.createDefault(
            baseSalesQty = baseSalesQty,
            growthPercent = growthPercent,
            price = price,
            rmCost = rmCost,
            laborRateVal = laborRateVal,
            varOverhead = varOverhead,
            fixedOH = fixedOH,
            fixedSA = fixedSA,
            depr = depr,
            initCashVal = initCashVal
        )
    }

    // Save project (either insert new or update existing)
    fun saveProject(projectName: String, onSuccess: () -> Unit) {
        viewModelScope.launch {
            val currentProj = currentProject.value
            if (currentProj != null) {
                // Update
                val updated = currentProj.copy(name = projectName, data = currentData.value)
                repository.update(updated)
                currentProject.value = updated
            } else {
                // Insert
                val newProj = Project(name = projectName, data = currentData.value)
                val id = repository.insert(newProj)
                currentProject.value = newProj.copy(id = id.toInt())
            }
            onSuccess()
        }
    }

    // Delete a project
    fun deleteProject(projectId: Int) {
        viewModelScope.launch {
            if (currentProject.value?.id == projectId) {
                currentProject.value = null
            }
            repository.deleteById(projectId)
        }
    }

    // Update specific inputs in working data
    fun updateWorkingData(updated: ProjectData) {
        currentData.value = updated
    }

    // Export to Excel / CSV
    fun exportToExcel(context: Context, engine: BudgetEngine, budgetName: String): String? {
        val fileName = "HoussemCompta_${budgetName.replace(" ", "_")}.csv"
        try {
            val file = File(context.getExternalFilesDir(null), fileName)
            val fos = FileOutputStream(file)
            
            // UTF-8 BOM for Excel Arabic support
            fos.write(0xEF)
            fos.write(0xBB)
            fos.write(0xBF)
            
            val writer = fos.writer(Charsets.UTF_8)
            writer.write("Houssem Compta - موازنة تقديرية لـ ${currentProject.value?.name ?: "مسودة جديدة"}\n")
            writer.write("جدول: $budgetName\n\n")
            
            // Generate header
            writer.write("البيان,")
            writer.write(ALGERIAN_MONTHS.joinToString(","))
            writer.write(",المجموع\n")

            // Write rows depending on budget name
            when (budgetName) {
                "المبيعات" -> {
                    writer.write("الكمية المباعة,${engine.data.salesQty.joinToString(",")},${engine.data.salesQty.sum()}\n")
                    writer.write("سعر البيع الأحادي (دج),${engine.data.unitPrice.joinToString(",")},-\n")
                    writer.write("رقم الأعمال التقديري (دج),${engine.salesRevenue.joinToString(",")},${engine.salesTotalRevenue}\n")
                    writer.write("المتحصلات النقدية (دج),${engine.salesCollections.joinToString(",")},${engine.salesCollections.sum()}\n")
                }
                "الإنتاج" -> {
                    writer.write("المبيعات المستهدفة,${engine.data.salesQty.joinToString(",")},${engine.data.salesQty.sum()}\n")
                    writer.write("مخزون آخر المدة المرغوب (وحدة),${engine.endingFG.joinToString(",")},-\n")
                    writer.write("إجمالي الاحتياجات,${engine.totalFGNeeded.joinToString(",")},${engine.totalFGNeeded.sum()}\n")
                    writer.write("مخزون أول المدة,${engine.beginningFG.joinToString(",")},-\n")
                    writer.write("الكمية الواجب إنتاجها,${engine.productionQty.joinToString(",")},${engine.productionQty.sum()}\n")
                }
                "المواد الأولية" -> {
                    writer.write("الكمية المنتجة,${engine.productionQty.joinToString(",")},${engine.productionQty.sum()}\n")
                    writer.write("معامل الاستهلاك للوحدة,${List(12) { engine.data.rawMaterialPerUnit }.joinToString(",")},-\n")
                    writer.write("إجمالي احتياجات الإنتاج (كغ),${engine.rawMaterialNeeded.joinToString(",")},${engine.rawMaterialNeeded.sum()}\n")
                }
                "المشتريات" -> {
                    writer.write("احتياج الإنتاج من المواد (كغ),${engine.rawMaterialNeeded.joinToString(",")},${engine.rawMaterialNeeded.sum()}\n")
                    writer.write("مخزون آخر المدة المرغوب (كغ),${engine.endingRM.joinToString(",")},-\n")
                    writer.write("إجمالي الاحتياجات,${engine.totalRMNeeded.joinToString(",")},${engine.totalRMNeeded.sum()}\n")
                    writer.write("مخزون أول المدة,${engine.beginningRM.joinToString(",")},-\n")
                    writer.write("الكمية الواجب شراؤها (كغ),${engine.rawMaterialToPurchase.joinToString(",")},${engine.rawMaterialToPurchase.sum()}\n")
                    writer.write("تكلفة شراء الكيلو (دج),${engine.data.rawMaterialCost.joinToString(",")},-\n")
                    writer.write("تكلفة الشراء الإجمالية (دج),${engine.purchasesCost.joinToString(",")},${engine.purchasesTotalCost}\n")
                    writer.write("المدفوعات النقدية للموردين (دج),${engine.purchasesPayments.joinToString(",")},${engine.purchasesPayments.sum()}\n")
                }
                "اليد العاملة المباشرة" -> {
                    writer.write("الكمية الواجب إنتاجها,${engine.productionQty.joinToString(",")},${engine.productionQty.sum()}\n")
                    writer.write("ساعات العمل المباشرة للوحدة,${List(12) { engine.data.laborHoursPerUnit }.joinToString(",")},-\n")
                    writer.write("إجمالي ساعات العمل المباشرة,${engine.laborHours.joinToString(",")},${engine.laborHours.sum()}\n")
                    writer.write("أجر الساعة (دج),${engine.data.laborRate.joinToString(",")},-\n")
                    writer.write("إجمالي تكلفة اليد العاملة (دج),${engine.laborCost.joinToString(",")},${engine.laborTotalCost}\n")
                }
                "المصاريف" -> {
                    writer.write("تكلفة المصاريف المتغيرة (دج),${engine.variableOverheadCost.joinToString(",")},${engine.variableOverheadCost.sum()}\n")
                    writer.write("المصاريف الثابتة (دج),${engine.data.fixedOverhead.joinToString(",")},${engine.data.fixedOverhead.sum()}\n")
                    writer.write("مصاريف البيع والإدارة (دج),${engine.data.fixedSAndA.joinToString(",")},${engine.data.fixedSAndA.sum()}\n")
                    writer.write("إجمالي المصاريف التقديرية (دج),${engine.totalOverheadAndSAndA.joinToString(",")},${engine.totalOverheadTotal}\n")
                    writer.write("منها الاهتلاكات (غير نقدية) (دج),${engine.data.depreciation.joinToString(",")},${engine.data.depreciation.sum()}\n")
                }
                "الخزينة" -> {
                    writer.write("رصيد أول المدة (دج),${engine.cashBeginning.joinToString(",")},-\n")
                    writer.write("متحصلات المقبوضات (دج),${engine.salesCollections.joinToString(",")},${engine.salesCollections.sum()}\n")
                    writer.write("مدفوعات المشتريات (دج),${engine.purchasesPayments.joinToString(",")},${engine.purchasesPayments.sum()}\n")
                    writer.write("مدفوعات اليد العاملة (دج),${engine.laborCost.joinToString(",")},${engine.laborTotalCost}\n")
                    writer.write("مدفوعات المصاريف النقدية (دج),${engine.cashExpenses.joinToString(",")},${engine.cashExpenses.sum()}\n")
                    writer.write("صافي التدفق النقدي (دج),${engine.cashNetFlow.joinToString(",")},${engine.cashNetFlow.sum()}\n")
                    writer.write("رصيد آخر المدة (دج),${engine.cashEnding.joinToString(",")},-\n")
                }
                "قائمة الدخل" -> {
                    writer.write("رقم الأعمال التقديري (دج),${engine.salesRevenue.joinToString(",")},${engine.salesTotalRevenue}\n")
                    writer.write("تكلفة المبيعات التقديرية (دج),${engine.cogs.joinToString(",")},${engine.totalCogs}\n")
                    writer.write("هامش الربح الإجمالي (دج),${engine.grossMargin.joinToString(",")},${engine.totalGrossMargin}\n")
                    writer.write("الأعباء الإدارية والبيعية (دج),${engine.operatingExpenses.joinToString(",")},${engine.totalOperatingExpenses}\n")
                    writer.write("النتيجة العملياتية (دج),${engine.netOperatingIncome.joinToString(",")},${engine.totalOperatingIncome}\n")
                    writer.write("الضرائب التقديرية (IBS 19%),${engine.ibsTax.joinToString(",")},${engine.totalTax}\n")
                    writer.write("النتيجة الصافية للدورة (دج),${engine.netIncome.joinToString(",")},${engine.totalNetIncome}\n")
                }
            }
            
            writer.flush()
            writer.close()
            fos.close()
            return file.absolutePath
        } catch (e: Exception) {
            e.printStackTrace()
            return null
        }
    }

    // Direct HTML-based Printing & PDF Generation
    fun printReport(context: Context, engine: BudgetEngine, title: String, contentHtml: String) {
        val webView = WebView(context)
        webView.webViewClient = object : WebViewClient() {
            override fun onPageFinished(view: WebView?, url: String?) {
                val printManager = context.getSystemService(Context.PRINT_SERVICE) as PrintManager
                val printAdapter = webView.createPrintDocumentAdapter(title)
                val jobName = "Houssem Compta - $title"
                printManager.print(jobName, printAdapter, PrintAttributes.Builder().build())
            }
        }
        webView.loadDataWithBaseURL(null, contentHtml, "text/html", "utf-8", null)
    }

    // Compile a beautiful full HTML Document
    fun generateFullHtmlReport(engine: BudgetEngine): String {
        val projectName = currentProject.value?.name ?: "مشروع تقديري جديد"
        
        val rowsSales = """
            <tr><td>الكمية المباعة</td>${engine.data.salesQty.joinToString("") { "<td>${String.format(Locale.US, "%,.0f", it)}</td>" }}<td>${String.format(Locale.US, "%,.0f", engine.data.salesQty.sum())}</td></tr>
            <tr><td>سعر البيع الأحادي (دج)</td>${engine.data.unitPrice.joinToString("") { "<td>${String.format(Locale.US, "%,.0f", it)}</td>" }}<td>-</td></tr>
            <tr class="highlight"><td>رقم الأعمال التقديري (دج)</td>${engine.salesRevenue.joinToString("") { "<td>${String.format(Locale.US, "%,.0f", it)}</td>" }}<td>${String.format(Locale.US, "%,.0f", engine.salesTotalRevenue)}</td></tr>
            <tr><td>المتحصلات النقدية (دج)</td>${engine.salesCollections.joinToString("") { "<td>${String.format(Locale.US, "%,.0f", it)}</td>" }}<td>${String.format(Locale.US, "%,.0f", engine.salesCollections.sum())}</td></tr>
        """.trimIndent()

        val rowsProduction = """
            <tr><td>المبيعات المستهدفة</td>${engine.data.salesQty.joinToString("") { "<td>${String.format(Locale.US, "%,.0f", it)}</td>" }}<td>${String.format(Locale.US, "%,.0f", engine.data.salesQty.sum())}</td></tr>
            <tr><td>مخزون آخر المدة المرغوب فيه</td>${engine.endingFG.joinToString("") { "<td>${String.format(Locale.US, "%,.0f", it)}</td>" }}<td>-</td></tr>
            <tr><td>إجمالي الاحتياجات</td>${engine.totalFGNeeded.joinToString("") { "<td>${String.format(Locale.US, "%,.0f", it)}</td>" }}<td>${String.format(Locale.US, "%,.0f", engine.totalFGNeeded.sum())}</td></tr>
            <tr><td>مخزون أول المدة</td>${engine.beginningFG.joinToString("") { "<td>${String.format(Locale.US, "%,.0f", it)}</td>" }}<td>-</td></tr>
            <tr class="highlight"><td>الكمية الواجب إنتاجها</td>${engine.productionQty.joinToString("") { "<td>${String.format(Locale.US, "%,.0f", it)}</td>" }}<td>${String.format(Locale.US, "%,.0f", engine.productionQty.sum())}</td></tr>
        """.trimIndent()

        val rowsPurchases = """
            <tr><td>الكمية الواجب إنتاجها</td>${engine.productionQty.joinToString("") { "<td>${String.format(Locale.US, "%,.0f", it)}</td>" }}<td>${String.format(Locale.US, "%,.0f", engine.productionQty.sum())}</td></tr>
            <tr><td>احتياج الإنتاج من المواد (كغ)</td>${engine.rawMaterialNeeded.joinToString("") { "<td>${String.format(Locale.US, "%,.0f", it)}</td>" }}<td>${String.format(Locale.US, "%,.0f", engine.rawMaterialNeeded.sum())}</td></tr>
            <tr><td>مخزون آخر المدة المرغوب (كغ)</td>${engine.endingRM.joinToString("") { "<td>${String.format(Locale.US, "%,.0f", it)}</td>" }}<td>-</td></tr>
            <tr><td>إجمالي الاحتياجات</td>${engine.totalRMNeeded.joinToString("") { "<td>${String.format(Locale.US, "%,.0f", it)}</td>" }}<td>${String.format(Locale.US, "%,.0f", engine.totalRMNeeded.sum())}</td></tr>
            <tr><td>مخزون أول المدة (كغ)</td>${engine.beginningRM.joinToString("") { "<td>${String.format(Locale.US, "%,.0f", it)}</td>" }}<td>-</td></tr>
            <tr class="highlight"><td>الكمية الواجب شراؤها (كغ)</td>${engine.rawMaterialToPurchase.joinToString("") { "<td>${String.format(Locale.US, "%,.0f", it)}</td>" }}<td>${String.format(Locale.US, "%,.0f", engine.rawMaterialToPurchase.sum())}</td></tr>
            <tr><td>تكلفة الشراء الإجمالية (دج)</td>${engine.purchasesCost.joinToString("") { "<td>${String.format(Locale.US, "%,.0f", it)}</td>" }}<td>${String.format(Locale.US, "%,.0f", engine.purchasesTotalCost)}</td></tr>
            <tr><td>المدفوعات النقدية للموردين (دج)</td>${engine.purchasesPayments.joinToString("") { "<td>${String.format(Locale.US, "%,.0f", it)}</td>" }}<td>${String.format(Locale.US, "%,.0f", engine.purchasesPayments.sum())}</td></tr>
        """.trimIndent()

        val rowsTreasury = """
            <tr><td>رصيد أول المدة (دج)</td>${engine.cashBeginning.joinToString("") { "<td>${String.format(Locale.US, "%,.0f", it)}</td>" }}<td>-</td></tr>
            <tr><td>المتحصلات الإجمالية (دج)</td>${engine.salesCollections.joinToString("") { "<td>${String.format(Locale.US, "%,.0f", it)}</td>" }}<td>${String.format(Locale.US, "%,.0f", engine.salesCollections.sum())}</td></tr>
            <tr><td>مدفوعات المشتريات (دج)</td>${engine.purchasesPayments.joinToString("") { "<td>${String.format(Locale.US, "%,.0f", it)}</td>" }}<td>${String.format(Locale.US, "%,.0f", engine.purchasesPayments.sum())}</td></tr>
            <tr><td>مدفوعات اليد العاملة (دج)</td>${engine.laborCost.joinToString("") { "<td>${String.format(Locale.US, "%,.0f", it)}</td>" }}<td>${String.format(Locale.US, "%,.0f", engine.laborTotalCost)}</td></tr>
            <tr><td>مدفوعات المصاريف التشغيلية (دج)</td>${engine.cashExpenses.joinToString("") { "<td>${String.format(Locale.US, "%,.0f", it)}</td>" }}<td>${String.format(Locale.US, "%,.0f", engine.cashExpenses.sum())}</td></tr>
            <tr class="highlight"><td>صافي التدفق النقدي (دج)</td>${engine.cashNetFlow.joinToString("") { "<td>${String.format(Locale.US, "%,.0f", it)}</td>" }}<td>${String.format(Locale.US, "%,.0f", engine.cashNetFlow.sum())}</td></tr>
            <tr class="highlight green-accent"><td>رصيد آخر المدة (دج)</td>${engine.cashEnding.joinToString("") { "<td>${String.format(Locale.US, "%,.0f", it)}</td>" }}<td>-</td></tr>
        """.trimIndent()

        val rowsIncome = """
            <tr><td>رقم الأعمال التقديري (دج)</td>${engine.salesRevenue.joinToString("") { "<td>${String.format(Locale.US, "%,.0f", it)}</td>" }}<td>${String.format(Locale.US, "%,.0f", engine.salesTotalRevenue)}</td></tr>
            <tr><td>تكلفة المبيعات (COGS) (دج)</td>${engine.cogs.joinToString("") { "<td>${String.format(Locale.US, "%,.0f", it)}</td>" }}<td>${String.format(Locale.US, "%,.0f", engine.totalCogs)}</td></tr>
            <tr class="highlight"><td>هامش الربح الإجمالي (دج)</td>${engine.grossMargin.joinToString("") { "<td>${String.format(Locale.US, "%,.0f", it)}</td>" }}<td>${String.format(Locale.US, "%,.0f", engine.totalGrossMargin)}</td></tr>
            <tr><td>الأعباء الإدارية والبيعية (دج)</td>${engine.operatingExpenses.joinToString("") { "<td>${String.format(Locale.US, "%,.0f", it)}</td>" }}<td>${String.format(Locale.US, "%,.0f", engine.totalOperatingExpenses)}</td></tr>
            <tr class="highlight"><td>النتيجة العملياتية (دج)</td>${engine.netOperatingIncome.joinToString("") { "<td>${String.format(Locale.US, "%,.0f", it)}</td>" }}<td>${String.format(Locale.US, "%,.0f", engine.totalOperatingIncome)}</td></tr>
            <tr><td>الضرائب المقدرة (IBS 19%)</td>${engine.ibsTax.joinToString("") { "<td>${String.format(Locale.US, "%,.0f", it)}</td>" }}<td>${String.format(Locale.US, "%,.0f", engine.totalTax)}</td></tr>
            <tr class="highlight green-accent"><td>النتيجة الصافية للدورة (دج)</td>${engine.netIncome.joinToString("") { "<td>${String.format(Locale.US, "%,.0f", it)}</td>" }}<td>${String.format(Locale.US, "%,.0f", engine.totalNetIncome)}</td></tr>
        """.trimIndent()

        // Balance sheet at December (month 11)
        val bs = engine.getBalanceSheet(11)
        val bsHtml = """
            <div class="balance-sheet-container">
                <div class="bs-col">
                    <h3>الأصول (Assets)</h3>
                    <table>
                        <thead>
                            <tr><th>العنصر</th><th>القيمة (دج)</th></tr>
                        </thead>
                        <tbody>
                            <tr><td>الأصول غير الجارية الصافية (التثبيتات)</td><td>${String.format(Locale.US, "%,.0f", bs.fixedAssetsNet)}</td></tr>
                            <tr><td>مخزون المواد الأولية</td><td>${String.format(Locale.US, "%,.0f", bs.rawMaterialInv)}</td></tr>
                            <tr><td>مخزون المنتجات التامة</td><td>${String.format(Locale.US, "%,.0f", bs.finishedGoodsInv)}</td></tr>
                            <tr><td>الحقوق والزبائن</td><td>${String.format(Locale.US, "%,.0f", bs.accountsReceivable)}</td></tr>
                            <tr class="highlight"><td>الخزينة (رصيد الخزينة النهائي)</td><td>${String.format(Locale.US, "%,.0f", bs.cash)}</td></tr>
                            <tr class="highlight green-accent"><td>إجمالي الأصول التقديرية</td><td>${String.format(Locale.US, "%,.0f", bs.totalAssets)}</td></tr>
                        </tbody>
                    </table>
                </div>
                <div class="bs-col">
                    <h3>الخصوم ورؤوس الأموال (Liabilities & Equity)</h3>
                    <table>
                        <thead>
                            <tr><th>العنصر</th><th>القيمة (دج)</th></tr>
                        </thead>
                        <tbody>
                            <tr><td>رأس المال الاجتماعي</td><td>${String.format(Locale.US, "%,.0f", bs.capital)}</td></tr>
                            <tr><td>النتائج المتراكمة والاحتياطات</td><td>${String.format(Locale.US, "%,.0f", bs.retainedEarnings)}</td></tr>
                            <tr class="highlight"><td>النتيجة الصافية للسنة المالية التقديرية</td><td>${String.format(Locale.US, "%,.0f", bs.currentNetIncome)}</td></tr>
                            <tr><td>ديون الموردين (الحسابات الدائنة)</td><td>${String.format(Locale.US, "%,.0f", bs.accountsPayable)}</td></tr>
                            <tr><td>الضرائب المستحقة الدفع (IBS)</td><td>${String.format(Locale.US, "%,.0f", bs.taxesPayable)}</td></tr>
                            <tr class="highlight green-accent"><td>إجمالي الخصوم ورؤوس الأموال التقديرية</td><td>${String.format(Locale.US, "%,.0f", bs.totalLiabilitiesAndEquity)}</td></tr>
                        </tbody>
                    </table>
                </div>
            </div>
        """.trimIndent()

        // Ratios
        val ratios = engine.getFinancialRatios(11)
        val ratiosHtml = """
            <div class="ratios-grid">
                <div class="ratio-card">
                    <h4>نسبة السيولة العامة (Current Ratio)</h4>
                    <p class="value">${String.format(Locale.US, "%.2f", ratios.currentRatio)}</p>
                    <p class="desc">القدرة على سداد الديون قصيرة الأجل (المعيار الممتاز > 1.0)</p>
                </div>
                <div class="ratio-card">
                    <h4>نسبة السيولة السريعة (Quick Ratio)</h4>
                    <p class="value">${String.format(Locale.US, "%.2f", ratios.quickRatio)}</p>
                    <p class="desc">سيولة الشركة الفورية بدون احتساب المخزونات</p>
                </div>
                <div class="ratio-card">
                    <h4>هامش الربح الإجمالي (Gross Margin %)</h4>
                    <p class="value">${String.format(Locale.US, "%.1f", ratios.grossProfitMargin)}%</p>
                    <p class="desc">كفاءة تسعير المنتجات وتكاليف الإنتاج المباشرة</p>
                </div>
                <div class="ratio-card">
                    <h4>هامش الربح الصافي (Net Margin %)</h4>
                    <p class="value">${String.format(Locale.US, "%.1f", ratios.netProfitMargin)}%</p>
                    <p class="desc">صافي الربح المحقق من كل دينار من المبيعات</p>
                </div>
            </div>
        """.trimIndent()

        return """
            <!DOCTYPE html>
            <html dir="rtl" lang="ar">
            <head>
                <meta charset="utf-8">
                <title>Houssem Compta - التقرير المالي التقديري</title>
                <style>
                    body {
                        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                        background-color: #ffffff;
                        color: #1a202c;
                        margin: 20px;
                        padding: 0;
                        line-height: 1.5;
                    }
                    .header {
                        text-align: center;
                        border-bottom: 3px double #0099ff;
                        padding-bottom: 15px;
                        margin-bottom: 30px;
                    }
                    .logo-name {
                        color: #0088e8;
                        font-size: 28px;
                        font-weight: bold;
                        margin: 0;
                    }
                    .sub-title {
                        color: #4a5568;
                        font-size: 16px;
                        margin: 5px 0 0 0;
                    }
                    h2 {
                        color: #0056b3;
                        border-right: 5px solid #0099ff;
                        padding-right: 10px;
                        margin-top: 40px;
                        font-size: 20px;
                        page-break-after: avoid;
                    }
                    table {
                        width: 100%;
                        border-collapse: collapse;
                        margin: 15px 0 25px 0;
                        font-size: 11px;
                    }
                    th, td {
                        border: 1px solid #cbd5e0;
                        padding: 6px 8px;
                        text-align: right;
                    }
                    th {
                        background-color: #f7fafc;
                        color: #2d3748;
                        font-weight: bold;
                    }
                    tr:nth-child(even) {
                        background-color: #f8fafc;
                    }
                    .highlight {
                        font-weight: bold;
                        background-color: #ebf8ff !important;
                    }
                    .green-accent {
                        background-color: #f0fff4 !important;
                        border: 2px solid #38a169;
                    }
                    .balance-sheet-container {
                        display: flex;
                        gap: 20px;
                        margin-bottom: 30px;
                    }
                    .bs-col {
                        flex: 1;
                    }
                    .ratios-grid {
                        display: grid;
                        grid-template-columns: repeat(2, 1fr);
                        gap: 15px;
                        margin-top: 15px;
                    }
                    .ratio-card {
                        border: 1px solid #cbd5e0;
                        border-radius: 8px;
                        padding: 15px;
                        background-color: #fcfcfc;
                    }
                    .ratio-card h4 {
                        margin: 0 0 5px 0;
                        color: #2b6cb0;
                        font-size: 13px;
                    }
                    .ratio-card .value {
                        font-size: 24px;
                        font-weight: bold;
                        margin: 0;
                        color: #2d3748;
                    }
                    .ratio-card .desc {
                        font-size: 10px;
                        color: #718096;
                        margin: 5px 0 0 0;
                    }
                    .footer-print {
                        text-align: center;
                        font-size: 10px;
                        color: #a0aec0;
                        margin-top: 50px;
                        border-top: 1px solid #e2e8f0;
                        padding-top: 10px;
                    }
                    @media print {
                        body { margin: 10px; }
                        h2 { margin-top: 30px; }
                        .page-break { page-break-before: always; }
                    }
                </style>
            </head>
            <body>
                <div class="header">
                    <h1 class="logo-name">Houssem Compta</h1>
                    <div class="sub-title">نظام إعداد الموازنات التقديرية الآلية والتحليل المالي</div>
                    <p style="font-size:12px; margin: 5px 0 0 0;">المشروع: <strong>$projectName</strong> | التاريخ: ${java.text.DateFormat.getDateInstance().format(java.util.Date())}</p>
                </div>

                <h2>1. الموازنة التقديرية للمبيعات</h2>
                <table>
                    <thead>
                        <tr><th>البيان</th>${ALGERIAN_MONTHS.joinToString("") { "<th>$it</th>" }}<th>المجموع</th></tr>
                    </thead>
                    <tbody>
                        $rowsSales
                    </tbody>
                </table>

                <h2>2. موازنة الإنتاج التقديرية</h2>
                <table>
                    <thead>
                        <tr><th>البيان</th>${ALGERIAN_MONTHS.joinToString("") { "<th>$it</th>" }}<th>المجموع</th></tr>
                    </thead>
                    <tbody>
                        $rowsProduction
                    </tbody>
                </table>

                <div class="page-break"></div>

                <h2>3. الموازنة التقديرية لمشتريات المواد الأولية</h2>
                <table>
                    <thead>
                        <tr><th>البيان</th>${ALGERIAN_MONTHS.joinToString("") { "<th>$it</th>" }}<th>المجموع</th></tr>
                    </thead>
                    <tbody>
                        $rowsPurchases
                    </tbody>
                </table>

                <h2>4. موازنة الخزينة التقديرية</h2>
                <table>
                    <thead>
                        <tr><th>البيان</th>${ALGERIAN_MONTHS.joinToString("") { "<th>$it</th>" }}<th>المجموع</th></tr>
                    </thead>
                    <tbody>
                        $rowsTreasury
                    </tbody>
                </table>

                <div class="page-break"></div>

                <h2>5. جدول حسابات النتائج التقديري (قائمة الدخل)</h2>
                <table>
                    <thead>
                        <tr><th>البيان</th>${ALGERIAN_MONTHS.joinToString("") { "<th>$it</th>" }}<th>المجموع</th></tr>
                    </thead>
                    <tbody>
                        $rowsIncome
                    </tbody>
                </table>

                <h2>6. الميزانية التقديرية المجمعة (نهاية السنة المالية)</h2>
                $bsHtml

                <h2>7. تحليل المؤشرات والنسب المالية التقديرية</h2>
                $ratiosHtml

                <div class="footer-print">
                    تم الإنشاء بواسطة تطبيق Houssem Compta الذكي - موازنات تقديرية بالطريقة الجزائرية وفق الـ SCF.
                </div>
            </body>
            </html>
        """.trimIndent()
    }
}
